### ISSUE TITLE
Failed to load a library: cairo / cairo-2

### ISSUE THREAD

**Issue by da-yaroslav-orel** [typhoon-hil/allure-docx#13]
Downloaded latest release: https://github.com/typhoon-hil/allure-docx/releases/download/v0.1.2/allure-docx.exe
When I try to generate docx file using the following commad:  
`allure-docx.exe D:\allure-results AllureReport.docx `
I get the following exception:
![image](https://user-images.githubusercontent.com/17005945/40839487-7a375026-65ab-11e8-9fad-1bfeed2496af.png)

I thought allure-docx.exe has all dependencies inside and there should be no need to install additional software. 
Anyway, then I installed Cairo using the following installer: 
`https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases `
and it didn't help. Exception still persists. 

Please help to resolve this issue.

**Comment by Sup3rGeo** [comment]
Hi! Thanks for trying it out!

The readme page points out that cairo dlls can be downloaded from here:

https://github.com/preshing/cairo-windows/releases

So try extracting one of the dlls (x86 or x64) to a folder and add that folder to the path. If it does not work with one version, try the other (but don't use both at the same time)

**Comment by da-yaroslav-orel** [comment]
Thanks. 32-bit version fixed this although my system is 64-bit
