### ISSUE TITLE
Create short version of report

### ISSUE THREAD

**Issue by da-yaroslav-orel** [typhoon-hil/allure-docx#14]
Hi. Thanks for the tool. 
I wonder if this is possible to make a shorter version of report? Current one has all the steps, stack traces etc and at the end even one our test generates 16 pages of docx file. With hundreds of tests it would be nightmare to navigate around it and collect necessary info.  For us it would be better to have something like Test Summary at the top (like in current version) and then list of passed and failed tests with fail messages (without stacktrace). What do you think about it?

**Comment by Sup3rGeo** [comment]
@da-yaroslav-orel hi!

That is indeed a great suggestion and probably I will be adding this as the next feature. This reduced version I believe should contain the test parameters as well as a minimum.

**Comment by yaroslav-orel** [comment]
@sup3rgeo great news. Looking forward to checking out next future release.

**Comment by Sup3rGeo** [comment]
@yaroslav-orel just published another release with an `--detail-level` option. Check it out and let us know what you think.

**Comment by da-yaroslav-orel** [comment]
Hi. I tried it for one test and it definitely looks better to my taste. Thank you very much. I also would appreciate fixing #16 because it's painful to edit json file before generating the report. And I would like to see how compact version of the report looks like with more than hundred tests.

**Comment by Sup3rGeo** [comment]
Closing this as it is already available. Any other change suggestions, if so, please open a new ticket. Thanks for helping!
