### ISSUE TITLE
Error when some of the properties are absent

### ISSUE THREAD

**Issue by ghost** [typhoon-hil/allure-docx#16]
Tool fails to generate report when test result json file has not such properties like "trace", "message" inside "statusDetails" etc. I had to manually edit test result file in order to generate docx file.

**Comment by Sup3rGeo** [comment]
Thanks for the report, I will tackle this the next iteration!

**Comment by Sup3rGeo** [comment]
@da-yaroslav-orel could you provide some example test results so I can analyze it and understand better why does it have statusDetails but not trace and message?

**Comment by Sup3rGeo** [comment]
Could you please try with the new release and let me know if problem is still present?
https://github.com/typhoon-hil/allure-docx/releases/tag/v0.3.0

(The test result files would still be very valuable for testing, if you could provide us them)

**Comment by Sup3rGeo** [comment]
@da-yaroslav-orel I will close this as inactive. You can check the latest 32-bit executable that has dlls bundled: https://github.com/typhoon-hil/allure-docx/releases/tag/v0.3.2
