### ISSUE TITLE
 why can't see  "-bash: allure-docx: command not found"??

### ISSUE THREAD

**Issue by szymon-glowa** [typhoon-hil/allure-docx#31]
MacBook-Pro-user:~ user$ pip install git+https://github.com/typhoon-hil/allure-docx.git
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/typhoon-hil/allure-docx.git
  Cloning https://github.com/typhoon-hil/allure-docx.git to /private/var/folders/gf/ykpgdfzj0bv6v1sm6rlp7mcr0000gn/T/pip-req-build-EgAOVr
Requirement already satisfied (use --upgrade to upgrade): allure-docx==0.3.2 from git+https://github.com/typhoon-hil/allure-docx.git in ./Library/Python/2.7/lib/python/site-packages
Requirement already satisfied: cairosvg in ./Library/Python/2.7/lib/python/site-packages (from allure-docx==0.3.2) (1.0.22)
Requirement already satisfied: click in ./Library/Python/2.7/lib/python/site-packages (from allure-docx==0.3.2) (7.1.2)
Requirement already satisfied: pygal in ./Library/Python/2.7/lib/python/site-packages (from allure-docx==0.3.2) (2.4.0)
Requirement already satisfied: python-docx in ./Library/Python/2.7/lib/python/site-packages (from allure-docx==0.3.2) (0.8.10)
Requirement already satisfied: cairocffi in ./Library/Python/2.7/lib/python/site-packages (from cairosvg->allure-docx==0.3.2) (0.9.0)
Requirement already satisfied: lxml>=2.3.2 in ./Library/Python/2.7/lib/python/site-packages (from python-docx->allure-docx==0.3.2) (4.6.1)
Requirement already satisfied: cffi>=1.1.0 in ./Library/Python/2.7/lib/python/site-packages (from cairocffi->cairosvg->allure-docx==0.3.2) (1.14.3)
Requirement already satisfied: pycparser in ./Library/Python/2.7/lib/python/site-packages (from cffi>=1.1.0->cairocffi->cairosvg->allure-docx==0.3.2) (2.20)
Building wheels for collected packages: allure-docx
  Building wheel for allure-docx (setup.py) ... done
  Created wheel for allure-docx: filename=allure_docx-0.3.2-py2-none-any.whl size=20064 sha256=4d0968935e0e52c2185b8bf4162a623fc5924795701bc68bb1dc15b7346a294e
  Stored in directory: /private/var/folders/gf/ykpgdfzj0bv6v1sm6rlp7mcr0000gn/T/pip-ephem-wheel-cache-Bi3FtK/wheels/5f/ba/1a/7863594f4a9e0988ef2c3d36860df4f7880e04416d0a71af08
Successfully built allure-docx
MacBook-Pro-user:~ user$ allure-docx
-bash: allure-docx: command not found

**Comment by Sup3rGeo** [comment]
Hi @szymon-glowa , this was not tested with python 2.7. Also make sure your Scripts python folder is in your PATH environment variable.

**Comment by szymon-glowa** [comment]
Thanks for the hint. The command: "sudo easy_install pip install git + https: //github.com/typhoon-hil/allure-docx.git" helped.
